---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
##
# Generate MN config iso
# 

#
# Static firstinstall config generation
#
- name: Creates  {{ vm_name }} directory
  local_action: file path={{ output_folder }} state=directory

- name: Creates {{ vm_name }} directory on remote server
  action: file path={{ output_folder }} state=directory

- name: "Generate {{ vm_name }} meta-data"
  local_action: template src=meta-data.ansible dest={{ output_folder }}/meta-data mode=0777
  with_items:
  - { instance_id: '{{ instance_id }}', hostname: '{{ vm_name }}' }

- name: Creates  {{ vm_type }} {{ vm_name }} directory
  local_action: template src={{ user_data_temp }} dest={{ output_folder }}/user-data mode=0777
  with_items:
  - { mn_config_type: '{{ mn_config_type }}'}
  when: vm_type == "mn"

- name: "Generate {{ vm_name }} user-data"
  local_action: template src={{ user_data_temp }} dest={{ output_folder }}/user-data mode=0777
  when: vm_type != "mn"

- name: "Generate {{ vm_name }} iso"
  local_action: shell /usr/bin/genisoimage -output {{ output_folder }}/{{ cloud_iso_name }} -volid cidata -joliet -rock {{ output_folder }}/user-data {{ output_folder }}/meta-data


