---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/create_site_deployment
 - include_vars: "{{ './' + site_dir + '/' + site_name + vars_files_override_postfix + '.yml' | default('') }}"

 - set_fact: xhost_numbers={{ vsphere_esxihostnames | length }}
   when: vsphere_esxihostnames is defined and deploy_platform == "deploy_vsphere"

 - set_fact: xhost_numbers={{ vsphere_esxihostnames_advanced | length }}
   when: vsphere_esxihostnames_advanced is defined and deploy_platform == "deploy_vsphere"

 - set_fact: xhost_numbers={{ baremetal_hpilohostnames | length }}
   when: baremetal_hpilohostnames is defined and deploy_platform == "deploy_baremetal"

 - set_fact: xhost_numbers = 1
   when: xhost_numbers is not defined

 - name: ""
   local_action: stat path={{ (base_path + "/custom-repos/system-repo") | realpath }}
   register: repoX

 - name: ""
   local_action: stat path={{ (base_path + "/../custom-repos/system-repo") | realpath }}
   register: repoX2
   when: repoX.stat.exists | bool == False

 - name: ""
   local_action: set_fact system_repo="system-repo"
   when: (repoX.stat.exists | bool == True) or (repoX2.stat.exists | bool == True)

 - name: "Creates a playbook"
   local_action: template src={{ playbook_template_file | default('role.ansible') }} dest=./{{ playbook_file_prefix }}{{ site_name }}.yml mode=0640

 - name: "Update playbook vars includes"
   local_action: lineinfile dest=./{{ playbook_file_prefix }}{{ site_name }}.yml regexp={{ item.var  }} line="    {{ item.var + item.file }}"
   with_items: custom_override_vars_files | default([])



