---
# tasks file for discover_network

- name: "Discover IPs"
  shell: "ip addr | awk '/inet/ && /{{hostvars.localhost.networks[item[1]].iface}}/{sub(/\\/.*$/,\"\",$2); print $2}'"
  register: ip
  delegate_to: "{{item[0]}}"
  with_nested:
    - "{{groups['all']|list}}"
    - "{{networks}}"

- name: Merge the hosts
  set_fact:
    networks: "{{networks|merge_ips(ip.results)}}"
