# Collect, aggregate, check the data
---

- name: Load autotune rule file if specified
  include_vars: "{{autotune_file}}"
  when: autotune_file is defined

- name: Add the autotune rules to the configuration
  set_fact:
    rules: "{{rules|merge_rules(loaded_rules)}}"
  when: autotune_file is defined

- name: "Parse the data"
  check:
    hostvars: "{{hostvars}}"
    rules:  "{{rules}}"
  run_once: yes

- name: "Analyze data"
  analyze:
    hostvars: "{{hostvars}}"
  delegate_to: localhost
  run_once: yes

- name: "Creating the Autotune Rules"
  tags:
    - autotune
  when: autotune_rules|length > 0 and create_autotune is defined
  template: "src=autotune.jinja dest={{output_dir}}/autotune.yml"
