---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/vm_remove_vsphere2
#- name

- name: "make sure poweroff {{ item }}"
  action:
    module: vsphere
    host: "{{ vsphere_vcenter }}"
    login: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    timeout: 60
    guest:
      name: "{{ item }}"
      state: shutdown
      force: True
  ignore_errors: yes
  with_items: vm_names
  when: force_remove | default(False) != True and force_remove | default(False) != "True"

- name: Force poweroff  
  action:
    module: vsphere_poweroff_vm
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ item }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ vsphere_esxihostname }}"
    folder_name: "{{ clusterid | default('') }}{{ system_versiontag | default('') }}"
    poweroff_mode: "hard"
  ignore_errors: yes
  with_items: vm_names
  when: force_remove | default(False) == True or force_remove | default(False) == "True"


- name: "Remove {{ item }}"
  action:
    module: vsphere
    host: "{{ vsphere_vcenter }}"
    login: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    timeout: 60
    guest:
      name: "{{ item }}"
      state: absent
  ignore_errors: yes
  with_items: vm_names

- debug: msg="removed {{ vm_names }}"


