{% raw %}
---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
#
# script-name: miit-nv.yml
#
# Ansible playbook used to verify network configuration.
# 
# usage: 
#     ansible-playbook miit-nv.yml -u root -i /<some-path->/hosts
# 
# check the generated html report with e.g. > firefox miit_report.html
#

#############################
## Environment Setup
#############################

- hosts: localhost
  name: Estimated Runtime

  tasks: 
    - debug:
        msg: {% endraw %}{{time_estimation}}{% raw %}
      name: Estimated Runtime

# Collect facts about the hosts and register the names
- hosts: all 
  name: Collect the facts about all the VMs 
 
  # If the fact is not "saved" this way it may or may not be really
  # set for further tasks depending on the host performing or not some task
  tasks:
    - name: Save the Name And Type
      set_fact:
        nv_name: "{{nv_name}}"
        nv_type: "{{nv_type}}"
      tags:
        - always

# Generate the ip register 
- hosts: localhost 
  name: Generate the ip register 

  tasks:
    - name: Create the ip_register
      ip_register:
        hostvars: "{{hostvars}}"
      tags:
        - always

#############################
## Performing Tests
#############################
{% endraw %}

{{ playbook.tasks|to_nice_yaml }}

{% raw %}
#############################
## Cleaning Up and Reporting 
#############################

# Collect Data and generate the report
- hosts: localhost
  name: Collect Data and generate the report
  gather_facts: no

  vars_files:
   - "{{rules_file}}" 

  vars:
   rules_file: vars/rules.yml

  roles:
   - { role: import_export, tags: ['import'], import: true }
   - { role: collect, tags: ['always'] }
   - { role: import_export, tags: ['export'], export: true }
   - { role: link_throughput_graph, tags: ['always'] }
   - { role: report, tags: ['always'] }
{% endraw %}
