---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# Internal network address for MN
os_msa_ipaddr: "{{ msa_ipaddr }}"
os_mn_oam_ip: "{{ mn_oam_ip }}"

os_dns_ips: "{{ dns_ips }}"
#ntphost1: 127.0.0.1
#ntphost2: 127.0.0.2
os_snmptrap_ip: "{{ snmptrap_ip }}"
os_snmp_port: "{{ snmp_port }}"

# Rela license server IP to be configured
os_licenseserver_ip: "{{ 127.0.0.1 }}"
