---
# Copyright (C) 2016 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/vm_deploy_pxe
#

#
# STEP 1: Create an empty VM
#
- name: "Vbox Createvm"
  action: shell sleep 0.1 ; vboxmanage createvm --name {{ vm_name_deploy }} --ostype "OpenSUSE_64" --groups "/{{ clusterid }}" --register ; sleep 0.2
  register: uuid
  
- add_host: name={{ vm_name_deploy }}.vbox groups=vbox uuid="{{ uuid.stdout_lines[1] | regex_replace('UUID'':'' ([0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})', '\\1') }}" clusterid={{ clusterid }} servername={{ vm_name_deploy }}

#
# STEP 2: Set VM boot order, add resources and storage
#
- name: "Vbox boot order conf"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --boot1 disk --boot2 net --boot3 none --boot4 none

- name: "Vbox CPU and Memory"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --memory {{ resource_mem_vm }} --cpus {{ resource_cpu_vm }}

- name: "Vbox storagectl add"
  action: command vboxmanage storagectl {{ hostvars[ vm_name_host_index ]['uuid'] }} --name "SATA Controller" --add sata --controller IntelAHCI --portcount 5

- name: "Sleep a litle bit"
  local_action: shell sleep 0.1

- name: "Vbox create harddrive"
  action: command vboxmanage createhd --filename {{ output_folder_remote | realpath }}/vm/{{ vm_name_deploy }}.vdi --size {{ rootdisk_size | int * 1024 }}

- name: "Vbox storageattach vdi"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium {{ output_folder_remote | realpath }}/vm/{{ vm_name_deploy }}.vdi  --setuuid ""

- name: "Vbox storagectl ide"
  action: command vboxmanage storagectl {{ hostvars[ vm_name_host_index ]['uuid'] }} --name "IDE Controller" --add ide --portcount 2


#
# STEP 3: Add networks
#
- name: "Vbox NIC1"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic1 {{ vbox_nic_oam }} --{{ vbox_nic_oam_prefix }}{{ vbox_nic_oam_adaptername }}1 {{ vbox_net_oam }}
  when: (nic1_enable | default(0) == 1 and vbox_nic_oam != "natnetwork")

- name: "Vbox NIC1"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic1 {{ vbox_nic_oam }} --{{ vbox_nic_oam_prefix }}{{ vbox_nic_oam_adaptername }}1nat {{ vbox_net_oam }}
  when: (nic1_enable | default(0) == 1 and vbox_nic_oam == "natnetwork")

- name: "Vbox NIC2"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic2 {{ vbox_nic_internal }} --{{ vbox_nic_internal_prefix }}{{ vbox_nic_internal_adaptername }}2 {{ vbox_net_internal }}
  when: nic2_enable | default(0) == 1

- name: "Vbox NIC3"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic3 {{ vbox_nic_access }} --{{ vbox_nic_access_prefix }}{{ vbox_nic_access_adaptername }}3 {{ vbox_net_access }}
  when: nic3_enable | default(0) == 1 and (vm_type != "da" or (vm_type == "da" and controlplanesig_network is not defined)) 

- name: "Vbox NIC4"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic4 {{ vbox_nic_internet }} --{{ vbox_nic_internet_prefix }}{{ vbox_nic_internet_adaptername }}4 {{ vbox_net_internet }}
  when: (nic4_enable | default(0) == 1 and vbox_nic_internet != "natnetwork")

- name: "Vbox NIC4"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic4 {{ vbox_nic_internet }} --{{ vbox_nic_internet_prefix }}{{ vbox_nic_internet_adaptername }}4 {{ vbox_net_internet }}
  when: (nic4_enable | default(0) == 1 and vbox_nic_internet == "natnetwork")


#
# STEP 4: Disable first network in order to allow pxe boot to be successful on second interface
#
- name: "Disable Vbox NIC1"
  action: command vboxmanage modifyvm {{ hostvars[ vm_name_host_index ]['uuid'] }} --nic1 none
  when: (nic1_enable | default(0) )
# COMMENT: NEEDS to re-enable the NIC after first boot!


#
# STEP 5: Power on the node
#
# COMMENT: Before powering on the vm, the MACID of the network card has to be known and stored on the PXE server!
- name: "Powering on VM"
  action: command vboxmanage startvm {{ hostvars[ vm_name_host_index ]['uuid'] }}
