---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/prepare_custom_repos

- local_action: file path={{ output_folder }} state=directory mode=0755

- local_action: stat path={{ output_folder }}/../custom-repos
  register: specific_custom_repos

- local_action: stat path=../../custom-repos
  register: general_custom_repos
  
- name: "Create soft link" 
  local_action: shell ln -s ../custom-repos {{ output_folder }}/../custom-repos 
  when: not specific_custom_repos.stat.exists and general_custom_repos.stat.exists 

#- local_action: file path={{ output_folder }}/../custom-repos state=directory mode=0755
#  when: specific_custom_repos.stat.exists and not general_custom_repos.stat.exists 

- local_action: file path={{ output_folder }}/../custom-repos state=directory mode=0755
  when: not specific_custom_repos.stat.exists and not general_custom_repos.stat.exists 

- name: "Normalize path to custom-repos directory"
  local_action: shell readlink -m "{{ output_folder }}/../custom-repos"
  register: cmd_result4

- name: "Make sure custom repo directories exists"
  local_action: file path={{ cmd_result4.stdout }}/{{ item }} state=directory follow=yes
  with_items: custom_repos | default([]) + [ system_repo | default('') ]

- name: "Prepare custom repos for deployment customization"
  local_action: shell cd {{ cmd_result4.stdout }}/{{ item }} && createrepo .
  with_items: custom_repos | default([]) + [ system_repo | default('') ]

- include: "{{ cee_deploy_prefix | default('normal') }}_task.yml"

