---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# defaults file for roles/vm2_deploy_vbox
system_versiontag: ""
default_rootdisk_size: "20"
tools_rootdisk_size: "50"
cim_rootdisk_size: "40"
universalcache: False
std_rootdisk_size: "80"

