---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for network_remove_vbox

- name: "Vbox check hostonlyifs"
  action: shell vboxmanage list hostonlyifs
  register: hostonlyifs_list

- name: "Vbox remove dhcpservers"
  action: command vboxmanage dhcpserver remove --netname HostInterfaceNetworking-{{ item }}
  ignore_errors: yes
  with_items:
    - vboxnet0
    - vboxnet1
    - vboxnet2
    - vboxnet3
    - vboxnet4
    - vboxnet5
    - vboxnet6
  when: (hostonlyifs_list.stdout_lines | join('')) != "" 

- name: "Vbox remove hostonlyinterfaces"
  action: command vboxmanage hostonlyif remove {{ item }}
  ignore_errors: yes
  with_items:
    - vboxnet0
    - vboxnet1
    - vboxnet2
    - vboxnet3
    - vboxnet4
    - vboxnet5
    - vboxnet6
  when: (hostonlyifs_list.stdout_lines | join('')) != "" 

- name: "Vbox check natnets"
  action: shell vboxmanage list natnets
  register: natnets_list

- name: "Vbox remove dhcpservers NAT networks"
  action: command vboxmanage dhcpserver remove --netname {{ item }}
  ignore_errors: yes
  with_items:
    - vboxnet0nat
    - vboxnet1nat
    - vboxnet2nat
    - vboxnet3nat
    - vboxnet4nat
    - vboxnet5nat
    - vboxnet6nat
  when: (natnets_list.stdout_lines | join('')) != "" 

- name: "Vbox remove NAT networks"
  action: command vboxmanage natnetwork remove --netname {{ item }}
  ignore_errors: yes
  with_items:
    - vboxnet0nat
    - vboxnet1nat
    - vboxnet2nat
    - vboxnet3nat
    - vboxnet4nat
    - vboxnet5nat
    - vboxnet6nat
  when: (natnets_list.stdout_lines | join('')) != "" 

