---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
#
access_ip: "{{ (access_network | ipaddr('int') + (switch_id | int) + 1) | ipaddr('address') }}"
internet_ip: "{{ (internet_network | ipaddr('int') + (switch_id | int) + 1) | ipaddr('address') }}"
accessingress_ip: "{{ (accessingress_network | ipaddr('int') + (switch_id | int) + 1) | ipaddr('address') }}"
internetingress_ip: "{{ (internetingress_network | ipaddr('int') + (switch_id | int) + 1) | ipaddr('address') }}"
oam_ip: "{{ (oam_network | ipaddr('int') + (switch_id | int) + 1) | ipaddr('address') }}"
internal_ip: "{{ (internal_network | ipaddr('int') + (switch_id | int)) | ipaddr('address') }}"
controlplanesig_ip: "{{ (controlplanesig_network | default(0)  | ipaddr('int') + (switch_id | int)) | ipaddr('address') }}"


