---
# Copyright (C) 2016 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/prepare_config_pxe

#
# STEP 1: Get a node list from the target, unfiltered containing all cartridges
#
- name: "Detect all the nodes"
  moonshot_cmd:
    username: "{{ilo_username}}"
    password: "{{ilo_password}}"
    address: "{{ilo_address}}"
    cartridge_exclusion: "[]"
    action: get_nodes
  register: result

#
# STEP 2: Configure the DHCP server
#
- name: "Setting interface(s) for the DHCPv4 server to listen on"
  action: shell sed -i 's,^\(DHCPD_INTERFACE=\).*,\1"{{ tools_pxe_dhcp_interface }}",' /etc/sysconfig/dhcpd
  sudo: yes

- name: "Generate DHCP Configuration"
  template: src=dhcpd.conf.jinja dest=/etc/dhcpd.conf
  with_items:
    - { nodes: "{{ result.cmd_output }}" }
  sudo: yes

#
# STEP 3: Start the DHCP and atftp services
#
- name: "Restart DHCPD"
  service: name=dhcpd state=restarted
  sudo: yes

# Sometimes starting atftpd.socket wa needed. I'm still not sure of what's going on with this
- name: "Restart ATFTPD"
  service: name=atftpd state=restarted
  sudo: yes
