---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# vars file for roles/vm_config
# vm_name_deploy: "{{ vm_name + system_versiontag }}"
regexpression: '^[\.]{2}/[\.]{2}(.*)$'
www_rel_output_path: "{{ rel_base_path | regex_replace(regexpression, '\\\\1') }}"

