---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# vars file for roles/vm_config
bootproto_oam_i: static
bootproto_internal_i: dhcp
bootproto_access_i: dhcp
bootproto_internet_i: dhcp
bootproto_accessingress_i: dhcp
bootproto_internetingress_i: dhcp
bootproto_controlplanesig_i: dhcp
bootproto_custom1_network_i: dhcp

