# Generate the HTML Report
---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.

- name: Getting the date
  command: date
  register: report_date
  run_once: true

- name: Improving the date
  set_fact: "report_date='{{report_date.stdout}}'"
  run_once: true

- name: Assembling the Js files
  shell: "cat $(pwd)/roles/report/templates/js/*"
  register: js_file

- name: Assembling the CSS files
  shell: "cat roles/report/templates/css/*"
  register: css_file

- set_fact:
    css_file: "{{css_file.stdout}}"
    js_file: "{{js_file.stdout}}"

- name: Generating the report
  template: "src=index.html dest={{output_dir}}/report.html mode=0755"
  run_once: true

- debug: msg="Report output to {{output_dir | realpath }}/report.html"
  run_once: true

- name: Creating the subdirectory inside www
  file: "path={{www_folder}}/system-verification state=directory mode=755"
  tags:
    - apache

- name: Create the simlink to the report
  file: "src={{output_dir}}/report.html dest={{www_folder}}/system-verification/report.html state=link"
  sudo: yes
  tags:
    - apache

- name: "Determine IP address of web server" 
  shell: "ip addr | awk '/inet/ && /{{ msp_tools_webserver_if | default('eth0') }}/{sub(/\\/.*$/,\"\",$2); print $2}'"
  register: web_ip

- name: Report Address
  debug: msg="http://{{web_ip.stdout_lines[0]}}/miit/{{outputdir + '/' if outputdir|length > 0 else ''}}system-verification/report.html"
  tags:
    - apache
