---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
dependencies:
- { role: net_create_vbox, vbox_net_name: "{{ oam_name }}", vbox_net_number: "0", vbox_nic_type: "{{ vbox_nic_oam }}", vbox_net_gateway: "{{ oam_gateway }}", vbox_net_netmask: "{{ oam_netmask }}", vbox_net_cidr: "{{ oam_cidr | default(24) }}", vbox_net_network: "{{ oam_network }}", vbox_net_network_vbox: "{{ oam_network_vbox }}", vbox_net_prefix: "{{ oam_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ oam_network_ipv6_prefix | default() }}", vbox_net_ipv6_gateway: "{{ oam_gateway_ipv6 | default() }}", vbox_net_ipv6_cidr: "{{ oam_network_ipv6_cidr | default() }}", vbox_net_network_lowerip: "{{ oam_network_lowerip }}", vbox_net_network_upperip: "{{ oam_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ internal_name }}", vbox_net_number: "1", vbox_nic_type: "{{ vbox_nic_internal }}", vbox_net_gateway: "{{ internal_gateway }}", vbox_net_netmask: "{{ internal_netmask }}", vbox_net_cidr: "{{ internal_cidr | default(24) }}", vbox_net_network: "{{ internal_network }}", vbox_net_network_vbox: "{{ internal_network_vbox }}", vbox_net_prefix: "{{ internal_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ internal_network_ipv6_prefix | default() }}", vbox_net_ipv6_gateway: "{{ internal_gateway_ipv6 | default() }}", vbox_net_ipv6_cidr: "{{ internal_network_ipv6_cidr | default() }}", vbox_net_network_lowerip: "{{ internal_network_lowerip }}", vbox_net_network_upperip: "{{ internal_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ access_name }}", vbox_net_number: "2", vbox_nic_type: "{{ vbox_nic_access }}", vbox_net_gateway: "{{ access_gateway }}", vbox_net_netmask: "{{ access_netmask }}", vbox_net_cidr: "{{ access_cidr | default(24) }}", vbox_net_network: "{{ access_network }}", vbox_net_network_vbox: "{{ access_network_vbox }}", vbox_net_prefix: "{{ access_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ access_network_ipv6_prefix | default('fc00:0:ca') }}", vbox_net_ipv6_gateway: "{{ access_gateway_ipv6 | default('fc00:0:ca::1') }}", vbox_net_ipv6_cidr: "{{ access_network_ipv6_cidr | default(48) }}", vbox_net_network_lowerip: "{{ access_network_lowerip }}", vbox_net_network_upperip: "{{ access_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ internet_name }}", vbox_net_number: "3", vbox_nic_type: "{{ vbox_nic_internet }}", vbox_net_gateway: "{{ internet_gateway }}", vbox_net_netmask: "{{ internet_netmask }}", vbox_net_cidr: "{{ internet_cidr | default(24) }}", vbox_net_network: "{{ internet_network }}", vbox_net_network_vbox: "{{ internet_network_vbox }}", vbox_net_prefix: "{{ internet_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ internet_network_ipv6_prefix | default('fc00:0:cb') }}", vbox_net_ipv6_gateway: "{{ internet_gateway_ipv6 | default('fc00:0:cb::1') }}", vbox_net_ipv6_cidr: "{{ internet_network_ipv6_cidr | default(48) }}", vbox_net_network_lowerip: "{{ internet_network_lowerip }}", vbox_net_network_upperip: "{{ internet_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ accessingress_name }}", vbox_net_number: "4", vbox_nic_type: "{{ vbox_nic_accessingress }}", vbox_net_gateway: "{{ accessingress_gateway }}", vbox_net_netmask: "{{ accessingress_netmask }}", vbox_net_cidr: "{{ accessingress_cidr | default(24) }}", vbox_net_network: "{{ accessingress_network }}", vbox_net_network_vbox: "{{ accessingress_network_vbox }}", vbox_net_prefix: "{{ accessingress_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ accessingress_network_ipv6_prefix | default('fc00:0:cc') }}", vbox_net_ipv6_gateway: "{{ accessingress_gateway_ipv6 | default('fc00:0:cc::1') }}", vbox_net_ipv6_cidr: "{{ accessingress_network_ipv6_cidr | default(48) }}", vbox_net_network_lowerip: "{{ accessingress_network_lowerip }}", vbox_net_network_upperip: "{{ accessingress_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ internetingress_name }}", vbox_net_number: "5", vbox_nic_type: "{{ vbox_nic_internetingress }}", vbox_net_gateway: "{{ internetingress_gateway }}", vbox_net_netmask: "{{ internetingress_netmask }}", vbox_net_cidr: "{{ internetingress_cidr | default(24) }}", vbox_net_network: "{{ internetingress_network }}", vbox_net_network_vbox: "{{ internetingress_network_vbox }}", vbox_net_prefix: "{{ internetingress_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ internetingress_network_ipv6_prefix | default('fc00:0:cd') }}", vbox_net_ipv6_gateway: "{{ internetingress_gateway_ipv6 | default('fc00:0:cd::1') }}", vbox_net_ipv6_cidr: "{{ internetingress_network_ipv6_cidr | default(48) }}", vbox_net_network_lowerip: "{{ internetingress_network_lowerip }}", vbox_net_network_upperip: "{{ internetingress_network_upperip }}" }

- { role: net_create_vbox, vbox_net_name: "{{ controlplanesig_name }}", vbox_net_number: "6", vbox_nic_type: "{{ vbox_nic_controlplanesig }}", vbox_net_gateway: "{{ controlplanesig_gateway }}", vbox_net_netmask: "{{ controlplanesig_netmask }}", vbox_net_cidr: "{{ controlplanesig_cidr | default(24) }}", vbox_net_network: "{{ controlplanesig_network }}", vbox_net_network_vbox: "{{ controlplanesig_network_vbox }}", vbox_net_prefix: "{{ controlplanesig_network_prefix | default() }}", vbox_net_ipv6_prefix: "{{ controlplanesig_network_ipv6_prefix | default() }}", vbox_net_ipv6_gateway: "{{ controlplanesig_gateway_ipv6 | default() }}", vbox_net_ipv6_cidr: "{{ controlplanesig_network_ipv6_cidr | default() }}", vbox_net_network_lowerip: "{{ controlplanesig_network_lowerip }}", vbox_net_network_upperip: "{{ controlplanesig_network_upperip }}", when: controlplanesig_name is defined }


galaxy_info:
  author: your name
  description: 
  company: your company (optional)
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
  #
  #platforms:
  #- name: EL
  #  versions:
  #  - all
  #  - 5
  #  - 6
  #  - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: Amazon
  #  versions:
  #  - all
  #  - 2013.03
  #  - 2013.09
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  #- name: Ubuntu
  #  versions:
  #  - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
  #  - trusty
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  #- name: Debian
  #  versions:
  #  - all
  #  - etch
  #  - lenny
  #  - squeeze
  #  - wheezy
  #
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  #categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
  #- development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
#dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
