---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/vm2_execute_upgrade_vsphere
- name: "poweroff the old version and powerup the new version"
  action:
    module: vsphere_swap_vm
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ vsphere_esxihostname }}"
    poweron_delay: 3
    vm_name_old: "{{ item }}{{ version_old }}"
    vm_name_new: "{{ item }}{{ version_new }}"
    folder_name_old: "{{ clusterid }}{{ version_old }}"
    folder_name_new: "{{ clusterid }}{{ version_new }}"
    poweroff_mode: "soft"
  with_items: vm_base_names
  when: force_remove | default(False) != True and force_remove | default(False) != "True" 
#and (upgrade_rollower_optimized | default(True) == True or upgrade_rollower_optimized | default(True) == True)

- name: Force poweroff  
  action:
    module: vsphere_poweroff_vm
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ item }}{{ version_old }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ vsphere_esxihostname }}"
    poweroff_mode: "hard"
    folder_name: "{{ clusterid }}{{ version_old }}"
  ignore_errors: yes
  with_items: vm_base_names
  when: force_remove | default(False) == True or force_remove | default(False) == "True"

- name: msg="Start Server"
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{ item }}{{ version_new }}"
    state: powered_on
  with_items: vm_base_names
  when: (force_remove | default(False) == True or force_remove | default(False) == "True")
# and (vm_boot | default('True')) | bool

