# set or reset delay and packet loss in a interface
---

  # Delete the netem entries for any interface
- name: Reset delay and loss
  shell: "tc qdisc show | grep netem  | awk -F ' ' '{print $5}' | xargs -I iface tc qdisc del dev iface root"
  sudo: yes
  when: reset is defined and reset == true 

- name: Apply delay and loss 
  command: tc qdisc replace dev {{interface}} root netem delay {{delay}} loss {{loss}}
  sudo: yes
  when: not (reset is defined and reset == true)
