 heat_template_version: 2013-05-23
 description: Generic HOT template to define the flavors available/applicable to the MSP VMs
 parameters:
   flavor_name:
# Note: flavor name is not supported by HEAT due to potential conflicts.
# Flavors can only be applied using the flavor id
     type: string
     description: flavor name
   root_disk_size:
     type: number
     description: hardisk size
     default: 0
   ephemeral_disk_size:
     type: number
     description: temporary storage size
     default: 0
   ram_size:
     type: number
     description: memory size
   vcpus_number:
     type: number
     description: number of CPUs
 resources:
   msp_flavor:
     type: Ericsson::Nova::Flavor
     properties:
       disk: { get_param: root_disk_size }
       ephemeral: { get_param: ephemeral_disk_size }
       ram: { get_param: ram_size }
       vcpus: { get_param: vcpus_number }
 outputs:
   my_flavor_id:
     description: Resource id of flavor
     value: { get_resource: msp_flavor }
