 heat_template_version: 2013-05-23
 description: Generic HOT template to create each new neutron networks required by the MSP VMs
 parameters:
   net_name:
      type: string
      description: Name of network to be created
   subnet_name:
     type: string
     description: Name of the subnet
   net_cidr: 
      type: string
      description: network address (CIDR notation)
   net_gateway:
      type: string
      description: network gateway address
#   net_pool_start:
#      type: string
#      description: Start of network IP address allocation pool
#   net_pool_end:
#      type: string
#      description: End of network IP address allocation pool
 resources:
   my_net:
      type: OS::Neutron::Net
      properties:
         name: { get_param: net_name }
   my_subnet:
      type: OS::Neutron::Subnet
      properties:
         name: { get_param: subnet_name }
         network_id: { get_resource: my_net }
         cidr: { get_param: net_cidr }
         gateway_ip: { get_param: net_gateway }
# allocation pool if needed - maybe if condition
#         allocation_pools:
#           - start: { get_param: net_pool_start }
#             end: { get_param: net_pool_end }
 outputs: 
    my_net_id: 
      description: Resource id of network 
      value: { get_resource: my_net } 
    my_subnet_id:
      description: Resource id of network
      value: { get_resource: my_subnet }
