---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
- name: Creates Switch {{ switch_name }} directory
  local_action: file path={{ output_folder }}/switch/{{ switch_name }} state=directory

- name: "Generate switch configuration for {{ switch_name }}"
  local_action: template src={{ switch_template }}.cfg dest={{ output_folder }}/switch/{{ switch_name }}/{{ switch_name }}{{ switch_id | default('') }}.cfg mode=0777


