# Launch iperf and the launch the measurement
---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.

- name: Lauch iperf
  iperf3: action=start destination={{item}}
  delegate_to: "{{item}}"
  ignore_errors: yes
  with_items:
  - "{{destinations}}"
  register: started
  when: not (no_server is defined and no_server == true)

  # The the couple host:port where iperf server is launched
- name: Get the corresponding host:port 
  set_fact: 
     ahosts: "{{started.results|rejectattr('failed', 'defined')|map(attribute='result')|list}}"
  when: not (no_server is defined and no_server == true)

- name: Get the corresponding host:port from config
  set_fact:
     ahosts: "{{destinations}}"
  when: no_server is defined and no_server == true

- debug: msg="List of started servers_ {{ahosts}}"

- name: Perform Iperf test
  iperf3: action=test destination={{item.destination}} port={{item.port}} duration={{duration}}
  ignore_errors: yes
  when: item.destination not in ansible_all_ipv4_addresses # The host should not iperf himself
  with_items:
  - "{{ahosts}}"
  register: test_result

- name: Stop Iperf servers 
  command: "pkill -f 'iperf3 -s -p {{item.port}}'"
  ignore_errors: yes
  delegate_to: "{{item.destination}}"
  with_items:
  - "{{ahosts}}"
  when: not (no_server is defined and no_server == true)

- name: Merged the failed and successfull start results 
  set_fact:
    test_result:
      results:  "{{started.results|selectattr('failed', 'defined')|list|union(test_result.get('results', []))|list}}"
