---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/net_create_vbox

#vboxnet create
- name: "Vbox hostonlyif - {{ vbox_net_name }} create dumy"
  action: command vboxmanage hostonlyif create 

- name: "Vbox hostonlyif - {{ vbox_net_name }} remove dumy"
  action: command vboxmanage hostonlyif remove vboxnet{{ vbox_net_number }}
  when: vbox_nic_type == "hostonly"

- name: "Vbox hostonlyif recreate with IPs 1 - {{ vbox_net_name }}"
#  VBOX 4 comand replaced by new commands for VBOS 5 backward compatible with VBOX 4
#  action: command vboxmanage hostonlyif create ipconfig vboxnet{{ vbox_net_number }} --ip {{ vbox_net_gateway }} --netmask {{ vbox_net_netmask }}
  action: command vboxmanage hostonlyif create
  when: vbox_nic_type == "hostonly"

- name: "Vbox hostonlyif recreate with IPs 2 - {{ vbox_net_name }}"
  action: command vboxmanage hostonlyif ipconfig vboxnet{{ vbox_net_number }} --ip {{ vbox_net_gateway }} --netmask {{ vbox_net_netmask }}
  when: vbox_nic_type == "hostonly"

- name: "Vbox hostonlyif add with IPv6 - {{ vbox_net_name }}"
  action: command vboxmanage hostonlyif ipconfig vboxnet{{ vbox_net_number }} --ipv6 {{ vbox_net_ipv6_gateway }} --netmasklengthv6 {{ vbox_net_ipv6_cidr }}
  when: vbox_nic_type == "hostonly" and vbox_enable_ipv6 | default('False') == 'True'

- name: "Vbox NAT network - {{ vbox_net_name }}"
  action: command vboxmanage natnetwork add --netname vboxnet{{ vbox_net_number }}nat --network {{ vbox_net_network }}/{{ vbox_net_cidr | default(24)}} --enable 
  when: vbox_nic_type == "natnetwork" 
#--dhcp on

- name: "Vbox dhcpserver define - {{ vbox_net_name }}"
  action: command vboxmanage dhcpserver add --netname vboxnet{{ vbox_net_number }}nat --ip {{ vbox_net_network_vbox }} --netmask {{ vbox_net_netmask }} --lowerip {{ vbox_net_network_lowerip }} --upperip {{ vbox_net_network_upperip }} --enable
  when: vbox_nic_type == "natnetwork" 

- name: "Vbox dhcpserver define - {{ vbox_net_name }}"
  action: command vboxmanage dhcpserver add --ifname vboxnet{{ vbox_net_number }} --ip {{ vbox_net_network_vbox }} --netmask {{ vbox_net_netmask }} --lowerip {{ vbox_net_network_lowerip }} --upperip {{ vbox_net_network_upperip }}
  when: vbox_nic_type == "hostonly" 

- name: "Vbox dhcpserver enable - {{ vbox_net_name }}"
  action: command vboxmanage dhcpserver modify --ifname vboxnet{{ vbox_net_number }} --enable
  when: vbox_nic_type == "hostonly" 



