---
# tasks file for find_ilo

- set_fact:
    subnet: "{{network|gen_subnet}}"
  name: Generate the subnet Addresses

- name: Ping everyone
  ignore_errors: yes
  command: ping -c 1 -w 1 {{item}}
  with_items:
    - "{{subnet}}"
  register: ping_output

- set_fact:
    up: "{{ping_output.results|selectattr('rc', 'sameas', 0)|map(attribute='item')|list}}" 

- name: Export data to json
  template: src=export.json.jinja dest=/tmp/up.json
  tags:
    - export

- name: Export data to json
  template: src=export.json.jinja dest=/tmp/up_new.json
  tags:
    - import 

- name: Import the data from a json file
  command: "cat /tmp/up.json" 
  ignore_errors: yes
  register: cat_output
  tags:
    - import 

- name: Fail gracefully if file not found
  fail: msg="Impossible to read the import file"
  tags:
    - import 
  when: cat_output|failed

- name: Import the data from JSON 
  set_fact:
    up_old: "{{ cat_output.stdout|from_json }}"
  tags:
    - import 

- name: Compute the new up hosts
  set_fact:
    up_new: "{{up|difference(up_old)}}"
  tags:
    - import 

- debug: var=up_new
  tags:
    - import 
