---
# Copyright (C) 2015 by
# Ericsson AB
# S-164 83 Stockholm
# Sweden
# Tel: +46 10 719 00 00
#
# The program may be used and/or copied only with the written permission
# from Ericsson AB, or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the program
# has been supplied.
#
# All rights reserved.
# tasks file for roles/vm2_deploy_vbox
- debug: msg="{{ vm_name_deploy }}"


- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi
  register: p
  when: vm_type == "mn"

- name: "Vbox Createhd - DB"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi --size 10000
#  when: vm_type == "mn" and (p.stat.isfile is not defined or not p.stat.isfile) 
  when: vm_type == "mn" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi
  register: p
  when: vm_type == "mn"

- name: "Vbox Createhd - Arch"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi --size 10000
#  when: vm_type == "mn" and (p.stat.isfile is not defined or not p.stat.isfile)
  when: vm_type == "mn" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi
  register: p
  when: vm_type == "mn"

- name: "Vbox Createhd - Backup"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi --size 30000
#  when: vm_type == "mn" and (p.stat.isfile is not defined or not p.stat.isfile)
  when: vm_type == "mn" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi
  register: p
  when: vm_type == "mn"

- name: "Vbox Createhd - Misc"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi --size 10000
#  when: vm_type == "mn"  and (p.stat.isfile is not defined or not p.stat.isfile)
  when: vm_type == "mn" and vm_upgrade | bool == False

- name: "Vbox storagectl add db"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi --setuuid ""
  when: vm_type == "mn"

- name: "Vbox storagectl add arch"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 2 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi --setuuid ""
  when: vm_type == "mn"

- name: "Vbox storagectl add backup"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 3 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi --setuuid ""
  when: vm_type == "mn"

- name: "Vbox storagectl add misc"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 4 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi --setuuid ""
  when: vm_type == "mn"


######## MON extra DB disks

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi
  register: p
  when: vm_type == "mon"

- name: "Vbox Createhd - DB - MON"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi --size 10000
  when: vm_type == "mon" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi
  register: p
  when: vm_type == "mon"

- name: "Vbox Createhd - Arch - MON"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi --size 10000
  when: vm_type == "mon" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi
  register: p
  when: vm_type == "mon"

- name: "Vbox Createhd - Backup - MON"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi --size 30000
  when: vm_type == "mon" and vm_upgrade | bool == False

- stat: path={{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi
  register: p
  when: vm_type == "mon"

- name: "Vbox Createhd - Misc - MON"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi --size 10000
  when: vm_type == "mon" and vm_upgrade | bool == False

- name: "Vbox storagectl add db - MON"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-db.vdi --setuuid ""
  when: vm_type == "mon"

- name: "Vbox storagectl add arch - MON"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 2 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-arch.vdi --setuuid ""
  when: vm_type == "mon"

- name: "Vbox storagectl add backup - MON"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 3 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-backup.vdi --setuuid ""
  when: vm_type == "mon"

- name: "Vbox storagectl add misc - MON"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 4 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name_deploy }}-misc.vdi --setuuid ""
  when: vm_type == "mon"

####### End MON


- stat: path={{ output_folder_remote }}/vm/{{ vm_name }}-UC.vdi
  register: p
  when: vm_type == "ts"

- name: "Vbox Createhd - UC"
  action: command vboxmanage createhd --filename {{ output_folder_remote }}/vm/{{ vm_name }}-UC.vdi --size {{ resource_disk_uc | int * 1000 }}
  when: vm_type == "ts" and (universalcache | bool == True) and (p.stat.isfile is not defined or not p.stat.isfile)

- name: "Vbox storagectl add UC"
  action: command vboxmanage storageattach {{ hostvars[ vm_name_host_index ]['uuid'] }} --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium {{ output_folder_remote }}/vm/{{ vm_name }}-UC.vdi --setuuid ""
  when: vm_type == "ts" and (universalcache | bool == True) and (vm_boot | default('True')) | bool

- name: "Vbox set time vm"
  action: command vboxmanage setextradata {{ hostvars[ vm_name_host_index ]['uuid'] }} "VBoxInternal/Devices/mc146818/0/Config/UseUTC" 1

- name: "Vbox startvm"
  action: command vboxmanage startvm {{ hostvars[ vm_name_host_index ]['uuid'] }}
#  ignore_errors: yes
  when: (vm_boot | default('True')) | bool

